/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as BillingNewRouteImport } from './routes/billing.new'
import { Route as QuotationNewRouteImport } from './routes/quotation.new'
import { Route as BillingIdEditRouteImport } from './routes/billing.$id.edit'
import { Route as QuotationIdEditRouteImport } from './routes/quotation.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingNewRoute = BillingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BillingRoute,
} as any)
const QuotationNewRoute = QuotationNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotationRoute,
} as any)
const BillingIdEditRoute = BillingIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => BillingRoute,
} as any)
const QuotationIdEditRoute = QuotationIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => QuotationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/quotation': typeof QuotationRouteWithChildren
  '/billing/new': typeof BillingNewRoute
  '/quotation/new': typeof QuotationNewRoute
  '/billing/$id/edit': typeof BillingIdEditRoute
  '/quotation/$id/edit': typeof QuotationIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/quotation': typeof QuotationRouteWithChildren
  '/billing/new': typeof BillingNewRoute
  '/quotation/new': typeof QuotationNewRoute
  '/billing/$id/edit': typeof BillingIdEditRoute
  '/quotation/$id/edit': typeof QuotationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/quotation': typeof QuotationRouteWithChildren
  '/billing/new': typeof BillingNewRoute
  '/quotation/new': typeof QuotationNewRoute
  '/billing/$id/edit': typeof BillingIdEditRoute
  '/quotation/$id/edit': typeof QuotationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/quotation'
    | '/billing/new'
    | '/quotation/new'
    | '/billing/$id/edit'
    | '/quotation/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/quotation'
    | '/billing/new'
    | '/quotation/new'
    | '/billing/$id/edit'
    | '/quotation/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/quotation'
    | '/billing/new'
    | '/quotation/new'
    | '/billing/$id/edit'
    | '/quotation/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRouteWithChildren
  QuotationRoute: typeof QuotationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/new': {
      id: '/billing/new'
      path: '/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof BillingNewRouteImport
      parentRoute: typeof BillingRoute
    }
    '/quotation/new': {
      id: '/quotation/new'
      path: '/new'
      fullPath: '/quotation/new'
      preLoaderRoute: typeof QuotationNewRouteImport
      parentRoute: typeof QuotationRoute
    }
    '/billing/$id/edit': {
      id: '/billing/$id/edit'
      path: '/$id/edit'
      fullPath: '/billing/$id/edit'
      preLoaderRoute: typeof BillingIdEditRouteImport
      parentRoute: typeof BillingRoute
    }
    '/quotation/$id/edit': {
      id: '/quotation/$id/edit'
      path: '/$id/edit'
      fullPath: '/quotation/$id/edit'
      preLoaderRoute: typeof QuotationIdEditRouteImport
      parentRoute: typeof QuotationRoute
    }
  }
}

interface BillingRouteChildren {
  BillingNewRoute: typeof BillingNewRoute
  BillingIdEditRoute: typeof BillingIdEditRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingNewRoute: BillingNewRoute,
  BillingIdEditRoute: BillingIdEditRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface QuotationRouteChildren {
  QuotationNewRoute: typeof QuotationNewRoute
  QuotationIdEditRoute: typeof QuotationIdEditRoute
}

const QuotationRouteChildren: QuotationRouteChildren = {
  QuotationNewRoute: QuotationNewRoute,
  QuotationIdEditRoute: QuotationIdEditRoute,
}

const QuotationRouteWithChildren = QuotationRoute._addFileChildren(
  QuotationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRouteWithChildren,
  QuotationRoute: QuotationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
